//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consoleT_Rex_Miner_01 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class appConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static appConfig defaultInstance = ((appConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appConfig())));
        
        public static appConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int Check_Every_Sec {
            get {
                return ((int)(this["Check_Every_Sec"]));
            }
            set {
                this["Check_Every_Sec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public double Min_Hashrate {
            get {
                return ((double)(this["Min_Hashrate"]));
            }
            set {
                this["Min_Hashrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RebootAfter {
            get {
                return ((int)(this["RebootAfter"]));
            }
            set {
                this["RebootAfter"] = value;
            }
        }
    }
}
